# Generated by Django 2.2.5 on 2019-09-12 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pontos_turisticos',
            name='aprovado',
            field=models.BooleanField(default=False),
        ),
    ]
