# Generated by Django 2.2.5 on 2019-09-12 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atracoes', '0001_initial'),
        ('core', '0002_auto_20190912_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontos_turisticos',
            name='atracoes',
            field=models.ManyToManyField(to='atracoes.Atracao'),
        ),
    ]
