# Generated by Django 2.2.5 on 2019-09-13 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0001_initial'),
        ('core', '0003_pontos_turisticos_atracoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontos_turisticos',
            name='comentarios',
            field=models.ManyToManyField(to='comentarios.Comentarios'),
        ),
    ]
