# Generated by Django 2.2.5 on 2019-09-13 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0001_initial'),
        ('core', '0004_pontos_turisticos_comentarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontos_turisticos',
            name='avaliacoes',
            field=models.ManyToManyField(to='avaliacoes.Avaliacao'),
        ),
    ]
