# Generated by Django 2.2.5 on 2019-09-13 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enderecos', '0001_initial'),
        ('core', '0005_pontos_turisticos_avaliacoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontos_turisticos',
            name='enderecos',
            field=models.ManyToManyField(to='enderecos.Endereco'),
        ),
    ]
