# Generated by Django 2.2.5 on 2019-09-13 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190913_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pontos_turisticos',
            name='enderecos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='enderecos.Endereco'),
        ),
    ]
