# Generated by Django 2.2.5 on 2019-09-15 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20190913_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontos_turisticos',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='pontos_turisticos'),
        ),
    ]
