# Generated by Django 2.2.5 on 2019-09-18 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20190918_1921'),
    ]

    operations = [
        migrations.RenameField(
            model_name='docidentificacao',
            old_name='descritpion',
            new_name='description',
        ),
    ]
