# Generated by Django 2.2.5 on 2019-09-18 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20190918_1932'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pontos_turisticos',
            old_name='doc_indentificacao',
            new_name='doc_identificacao',
        ),
    ]
